DROP TABLE IF EXISTS `adm_metods_default-item`;

CREATE TABLE IF NOT EXISTS `adm_metods_default-item` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_module` varchar(255) NOT NULL,
  `metod` varchar(255) NOT NULL,
  `caption` varchar(255) NOT NULL,
  `properties` text,
  `flag_admin` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id_module` (`id_module`),
  KEY `metod` (`metod`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=569 ;

INSERT INTO `adm_metods_default-item` (`id`, `id_module`, `metod`, `caption`, `properties`, `flag_admin`) VALUES
(516, 'mapsite', 'pub_show_mapsite', '[#mapsite_show_map#]', 'a:2:{i:0;a:6:{s:4:"name";s:13:"id_page_start";s:7:"caption";s:32:"[#module_mapsite_id_page_start#]";s:4:"type";s:4:"page";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}}i:1;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:35:"[#module_mapsite_label_propertes1#]";s:4:"type";s:4:"file";s:7:"default";s:16:"mapsite/map.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"mapsite";s:4:"mask";s:8:"html,htm";}}', 1),
(534, 'menu', 'pub_show_menu', '[#menu_show_menu#]', 'a:4:{i:0;a:6:{s:4:"name";s:13:"id_page_start";s:7:"caption";s:30:"[#module_menu_id_page_start1#]";s:4:"type";s:4:"page";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}}i:1;a:8:{s:4:"name";s:17:"count_level_start";s:7:"caption";s:33:"[#module_menu_count_level_start#]";s:4:"type";s:6:"select";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:6:{i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";}s:14:"data_user_func";a:0:{}}i:2;a:8:{s:4:"name";s:16:"count_level_show";s:7:"caption";s:32:"[#module_menu_count_level_show#]";s:4:"type";s:6:"select";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:6:{i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";}s:14:"data_user_func";a:0:{}}i:3;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:32:"[#module_menu_label_propertes1#]";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:4:"menu";s:4:"mask";s:8:"html,htm";}}', 1),
(535, 'menu', 'pub_show_menu_static', '[#menu_show_menu_static#]', 'a:3:{i:0;a:6:{s:4:"name";s:13:"id_page_start";s:7:"caption";s:30:"[#module_menu_id_page_start1#]";s:4:"type";s:4:"page";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}}i:1;a:8:{s:4:"name";s:16:"count_level_show";s:7:"caption";s:32:"[#module_menu_count_level_show#]";s:4:"type";s:6:"select";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:6:{i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";}s:14:"data_user_func";a:0:{}}i:2;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:32:"[#module_menu_label_propertes1#]";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:4:"menu";s:4:"mask";s:8:"html,htm";}}', 1),
(536, 'comments', 'pub_show_comments', '[#comments_pub_show_comments#]', 'a:5:{i:0;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:39:"[#comments_pub_show_comments_template#]";s:4:"type";s:4:"file";s:7:"default";s:13:"comments.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:8:"comments";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:5:"limit";s:7:"caption";s:36:"[#comments_pub_show_comments_limit#]";s:4:"type";s:4:"text";s:7:"default";s:2:"10";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:2;a:8:{s:4:"name";s:4:"type";s:7:"caption";s:35:"[#comments_pub_show_comments_type#]";s:4:"type";s:6:"select";s:7:"default";s:7:"default";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:3:{s:7:"default";s:43:"[#comments_pub_show_comments_type_default#]";s:10:"new_at_top";s:46:"[#comments_pub_show_comments_type_new_at_top#]";s:13:"new_at_bottom";s:49:"[#comments_pub_show_comments_type_new_at_bottom#]";}s:14:"data_user_func";a:0:{}}i:3;a:8:{s:4:"name";s:10:"httpparams";s:7:"caption";s:41:"[#comments_pub_show_comments_httpparams#]";s:4:"type";s:4:"text";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:4;a:8:{s:4:"name";s:9:"no_parent";s:7:"caption";s:98:"Выводить блок комментариев на родительской странице?";s:4:"type";s:6:"select";s:7:"default";s:2:"no";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:2:{s:2:"no";s:29:"Нет, не выводить";s:3:"yes";s:22:"Да, выводить";}s:14:"data_user_func";a:0:{}}}', 1),
(537, 'waysite', 'pub_show_waysite', '[#waysite_pub_show_waysite#]', 'a:1:{i:0;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:35:"[#module_waysite_label_propertes1#]";s:4:"type";s:4:"file";s:7:"default";s:16:"waysite/way.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"waysite";s:4:"mask";s:8:"html,htm";}}', 1),
(538, 'waysite', 'pub_show_caption_static', '[#waysite_show_caption_static#]', 'a:1:{i:0;a:8:{s:4:"name";s:9:"level_num";s:7:"caption";s:28:"[#module_waysite_level_num#]";s:4:"type";s:4:"text";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1),
(551, 'catalog', 'get_count_offers', 'Вывести общее количество офферов', 'a:1:{i:0;a:8:{s:4:"name";s:20:"get_count_offers_tpl";s:7:"caption";s:25:"Шаблон вывода";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}}', 1),
(552, 'catalog', 'get_count_items', 'Вывести общее количество товаров', 'a:1:{i:0;a:8:{s:4:"name";s:19:"get_count_items_tpl";s:7:"caption";s:25:"Шаблон вывода";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}}', 1),
(553, 'catalog', 'pub_show_param_item_to_cat', 'Вывести некий параметр категории', 'a:2:{i:0;a:8:{s:4:"name";s:21:"param_item_to_cat_tpl";s:7:"caption";s:12:"Шаблон";s:4:"type";s:4:"file";s:7:"default";s:22:"param_item_to_cat.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:17:"param_item_to_cat";s:7:"caption";s:76:"Сво-во товара, которое необходимо вывести";s:4:"type";s:4:"text";s:7:"default";s:6:"vehdor";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:6;}}', 1),
(554, 'catalog', 'pub_catalog_show_coupon', 'Вывести купоны к товару', 'a:3:{i:0;a:8:{s:4:"name";s:10:"coupon_tpl";s:7:"caption";s:12:"Шаблон";s:4:"type";s:4:"file";s:7:"default";s:11:"coupon.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:12:"count_coupon";s:7:"caption";s:54:"Количество выводимых купонов";s:4:"type";s:4:"text";s:7:"default";s:1:"5";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:2;a:8:{s:4:"name";s:8:"date_end";s:7:"caption";s:53:"Формат даты окончания купона";s:4:"type";s:4:"text";s:7:"default";s:5:"d.m.Y";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1),
(555, 'catalog', 'pub_catalog_show_cats', '[#catalog_show_cats#]', 'a:4:{i:0;a:8:{s:4:"name";s:7:"cat_tpl";s:7:"caption";s:15:"[#catalog_tpl#]";s:4:"type";s:4:"file";s:7:"default";s:15:"categories.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:33:"catalog_categories_build_from_cat";s:7:"caption";s:43:"[#catalog_categories_build_from_cat_label#]";s:4:"type";s:4:"text";s:7:"default";s:1:"0";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:2;a:8:{s:4:"name";s:35:"catalog_categories_open_levels_show";s:7:"caption";s:45:"[#catalog_categories_open_levels_show_label#]";s:4:"type";s:6:"select";s:7:"default";s:1:"1";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:7:{i:0;s:1:"0";i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";}s:14:"data_user_func";a:0:{}}i:3;a:8:{s:4:"name";s:34:"catalog_categories_max_levels_show";s:7:"caption";s:44:"[#catalog_categories_max_levels_show_label#]";s:4:"type";s:6:"select";s:7:"default";s:1:"3";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:7:{i:0;s:1:"0";i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";}s:14:"data_user_func";a:0:{}}}', 1),
(556, 'catalog', 'get_items_like', 'Вывести похожие товары', 'a:3:{i:0;a:8:{s:4:"name";s:10:"items_left";s:7:"caption";s:22:"Кол-во слева";s:4:"type";s:4:"text";s:7:"default";s:1:"2";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:1;a:8:{s:4:"name";s:11:"items_right";s:7:"caption";s:24:"Кол-во справа";s:4:"type";s:4:"text";s:7:"default";s:1:"2";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:2;a:8:{s:4:"name";s:14:"items_like_tpl";s:7:"caption";s:12:"Шаблон";s:4:"type";s:4:"file";s:7:"default";s:9:"list.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}}', 1),
(557, 'catalog', 'get_items_best_clik', 'Вывести самые кликабельные товары', 'a:2:{i:0;a:8:{s:4:"name";s:13:"best_clik_tpl";s:7:"caption";s:25:"Шаблон вывода";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:21:"count_items_best_clik";s:7:"caption";s:54:"Количество выводимых товаров";s:4:"type";s:4:"text";s:7:"default";s:1:"3";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1),
(558, 'catalog', 'pub_catalog_show_items', '[#catalog_show_items#]', 'a:3:{i:0;a:8:{s:4:"name";s:14:"items_per_page";s:7:"caption";s:32:"[#catalog_items_per_page_label#]";s:4:"type";s:4:"text";s:7:"default";s:2:"20";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:1;a:6:{s:4:"name";s:24:"show_cats_if_empty_items";s:7:"caption";s:42:"[#catalog_show_cats_if_empty_items_label#]";s:4:"type";s:5:"check";s:7:"default";s:1:"1";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}}i:2;a:8:{s:4:"name";s:13:"item_list_tpl";s:7:"caption";s:25:"[#catalog_cats_list_tpl#]";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"catalog";s:4:"mask";s:8:"htm,html";}}', 1),
(559, 'catalog', 'pub_catalog_show_item_name', '[#catalog_show_item_name#]', 'a:4:{i:0;a:8:{s:4:"name";s:18:"title_page_catalog";s:7:"caption";s:71:"title, keywords или description у страницы каталога";s:4:"type";s:4:"text";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:1;a:8:{s:4:"name";s:24:"catalog_show_item_fields";s:7:"caption";s:34:"[#catalog_show_item_fields_label#]";s:4:"type";s:4:"text";s:7:"default";s:6:"%name%";s:11:"description";s:0:"";s:21:"description_user_func";a:3:{s:8:"filepath";s:41:"modules/catalog/catalog.commons.class.php";s:4:"name";a:2:{i:0;s:14:"CatalogCommons";i:1;s:24:"get_all_group_props_html";}s:5:"param";b:0;}s:3:"max";s:3:"255";s:4:"size";i:6;}i:2;a:8:{s:4:"name";s:23:"catalog_show_cat_fields";s:7:"caption";s:33:"[#catalog_show_cat_fields_label#]";s:4:"type";s:4:"text";s:7:"default";s:6:"%name%";s:11:"description";s:0:"";s:21:"description_user_func";a:3:{s:8:"filepath";s:41:"modules/catalog/catalog.commons.class.php";s:4:"name";a:2:{i:0;s:14:"CatalogCommons";i:1;s:19:"get_cats_props_html";}s:5:"param";b:0;}s:3:"max";s:3:"255";s:4:"size";i:6;}i:3;a:8:{s:4:"name";s:14:"page_delemiter";s:7:"caption";s:158:"Разделитель, после которого выводится номер страницы при просмотре товаров катагорий";s:4:"type";s:4:"text";s:7:"default";s:25:"/ страница %page%";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:17;}}', 1),
(560, 'catalog', 'pub_catalog_show_inner_selection_results', '[#catalog_show_inner_selection_results#]', 'a:1:{i:0;a:8:{s:4:"name";s:32:"catalog_inner_selection_stringid";s:7:"caption";s:40:"[#catalog_inner_selection_filter_label#]";s:4:"type";s:6:"select";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:0:{}s:14:"data_user_func";a:3:{s:8:"filepath";s:41:"modules/catalog/catalog.commons.class.php";s:4:"name";a:2:{i:0;s:14:"CatalogCommons";i:1;s:25:"get_inner_filters_kvarray";}s:5:"param";b:0;}}}', 1),
(561, 'banners', 'pub_show_banners', '[#banners_show_banner#]', 'a:2:{i:0;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:38:"[#module_banners_template_propertes1#]";s:4:"type";s:4:"file";s:7:"default";s:11:"banner.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"banners";s:4:"mask";s:8:"html,htm";}i:1;a:8:{s:4:"name";s:8:"group_id";s:7:"caption";s:35:"[#module_banners_group_propertes1#]";s:4:"type";s:6:"select";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:0:{}s:14:"data_user_func";a:3:{s:8:"filepath";s:41:"modules/banners/banners.commons.class.php";s:4:"name";a:2:{i:0;s:14:"BannersCommons";i:1;s:14:"get_group_html";}s:5:"param";b:0;}}}', 1),
(562, 'innerseo', 'pub_show_ancors', 'Вывести анкоры', 'a:2:{i:0;a:8:{s:4:"name";s:15:"show_ancors_tpl";s:7:"caption";s:12:"Шаблон";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:8:"innerseo";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:11:"limit_ancor";s:7:"caption";s:35:"Количество анкоров";s:4:"type";s:4:"text";s:7:"default";s:1:"3";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1),
(563, 'innerseo', 'pub_show_rand_ancors', 'Рандомно вывести анкоры', 'a:2:{i:0;a:8:{s:4:"name";s:15:"show_ancors_tpl";s:7:"caption";s:12:"Шаблон";s:4:"type";s:4:"file";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:8:"innerseo";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:11:"limit_ancor";s:7:"caption";s:35:"Количество анкоров";s:4:"type";s:4:"text";s:7:"default";s:1:"3";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1),
(564, 'evalmod', 'pub_eval_file_set', 'Выполнить PHP код из файла', 'a:1:{i:0;a:8:{s:4:"name";s:14:"including_file";s:7:"caption";s:17:"Имя файла";s:4:"type";s:4:"file";s:7:"default";s:16:"evalmod/test.php";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:7:"evalmod";s:4:"mask";s:3:"php";}}', 1),
(565, 'newsi', 'pub_show_keywords', 'Вывести keywords новости', 'a:0:{}', 1),
(566, 'newsi', 'pub_show_description', 'Вывести description новости', 'a:0:{}', 1),
(567, 'newsi', 'pub_show_lenta', '[#news_pub_show_lenta#]', 'a:5:{i:0;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:32:"[#news_pub_show_lenta_template#]";s:4:"type";s:4:"file";s:7:"default";s:10:"lenta.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:5:"newsi";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:5:"limit";s:7:"caption";s:29:"[#news_pub_show_lenta_limit#]";s:4:"type";s:4:"text";s:7:"default";s:2:"10";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:2;a:8:{s:4:"name";s:4:"type";s:7:"caption";s:28:"[#news_pub_show_lenta_type#]";s:4:"type";s:6:"select";s:7:"default";s:7:"default";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:3:{s:7:"default";s:36:"[#news_pub_show_lenta_type_default#]";s:4:"past";s:33:"[#news_pub_show_lenta_type_past#]";s:6:"future";s:35:"[#news_pub_show_lenta_type_future#]";}s:14:"data_user_func";a:0:{}}i:3;a:6:{s:4:"name";s:4:"page";s:7:"caption";s:28:"[#news_pub_show_lenta_page#]";s:4:"type";s:4:"page";s:7:"default";s:5:"index";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}}i:4;a:8:{s:4:"name";s:10:"id_modules";s:7:"caption";s:34:"[#news_pub_show_lenta_id_modules#]";s:4:"type";s:4:"text";s:7:"default";s:0:"";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1),
(568, 'newsi', 'pub_show_archive', '[#news_pub_show_archive#]', 'a:5:{i:0;a:8:{s:4:"name";s:8:"template";s:7:"caption";s:34:"[#news_pub_show_archive_template#]";s:4:"type";s:4:"file";s:7:"default";s:17:"newsi/arhive.html";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:5:"patch";s:5:"newsi";s:4:"mask";s:8:"htm,html";}i:1;a:8:{s:4:"name";s:5:"limit";s:7:"caption";s:31:"[#news_pub_show_archive_limit#]";s:4:"type";s:4:"text";s:7:"default";s:2:"10";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}i:2;a:8:{s:4:"name";s:4:"type";s:7:"caption";s:30:"[#news_pub_show_archive_type#]";s:4:"type";s:6:"select";s:7:"default";s:7:"default";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:3:{s:7:"default";s:33:"[#news_pub_show_archive_default#]";s:4:"past";s:30:"[#news_pub_show_archive_past#]";s:6:"future";s:32:"[#news_pub_show_archive_future#]";}s:14:"data_user_func";a:0:{}}i:3;a:8:{s:4:"name";s:10:"pages_type";s:7:"caption";s:23:"[#news_pub_pages_type#]";s:4:"type";s:6:"select";s:7:"default";s:5:"block";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:4:"data";a:2:{s:5:"block";s:28:"[#news_pub_pages_get_block#]";s:5:"float";s:28:"[#news_pub_pages_get_float#]";}s:14:"data_user_func";a:0:{}}i:4;a:8:{s:4:"name";s:11:"pages_count";s:7:"caption";s:29:"[#news_property_pages_count#]";s:4:"type";s:4:"text";s:7:"default";s:1:"5";s:11:"description";s:0:"";s:21:"description_user_func";a:0:{}s:3:"max";s:3:"255";s:4:"size";i:5;}}', 1);
